
package co.igb.transportws.client.coordinadora.ags;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "RpcServerSoapManagerService", targetNamespace = "https://sandbox.coordinadora.com/ags/1.5/server.php", wsdlLocation = "https://sandbox.coordinadora.com/ags/1.5/server.php?wsdl")
public class RpcServerSoapManagerService
    extends Service
{

    private final static URL RPCSERVERSOAPMANAGERSERVICE_WSDL_LOCATION;
    private final static WebServiceException RPCSERVERSOAPMANAGERSERVICE_EXCEPTION;
    private final static QName RPCSERVERSOAPMANAGERSERVICE_QNAME = new QName("https://sandbox.coordinadora.com/ags/1.5/server.php", "RpcServerSoapManagerService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("https://sandbox.coordinadora.com/ags/1.5/server.php?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        RPCSERVERSOAPMANAGERSERVICE_WSDL_LOCATION = url;
        RPCSERVERSOAPMANAGERSERVICE_EXCEPTION = e;
    }

    public RpcServerSoapManagerService() {
        super(__getWsdlLocation(), RPCSERVERSOAPMANAGERSERVICE_QNAME);
    }

    public RpcServerSoapManagerService(WebServiceFeature... features) {
        super(__getWsdlLocation(), RPCSERVERSOAPMANAGERSERVICE_QNAME, features);
    }

    public RpcServerSoapManagerService(URL wsdlLocation) {
        super(wsdlLocation, RPCSERVERSOAPMANAGERSERVICE_QNAME);
    }

    public RpcServerSoapManagerService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, RPCSERVERSOAPMANAGERSERVICE_QNAME, features);
    }

    public RpcServerSoapManagerService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public RpcServerSoapManagerService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns RpcServerSoapManagerPort
     */
    @WebEndpoint(name = "RpcServerSoapManagerPort")
    public RpcServerSoapManagerPort getRpcServerSoapManagerPort() {
        return super.getPort(new QName("https://sandbox.coordinadora.com/ags/1.5/server.php", "RpcServerSoapManagerPort"), RpcServerSoapManagerPort.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns RpcServerSoapManagerPort
     */
    @WebEndpoint(name = "RpcServerSoapManagerPort")
    public RpcServerSoapManagerPort getRpcServerSoapManagerPort(WebServiceFeature... features) {
        return super.getPort(new QName("https://sandbox.coordinadora.com/ags/1.5/server.php", "RpcServerSoapManagerPort"), RpcServerSoapManagerPort.class, features);
    }

    private static URL __getWsdlLocation() {
        if (RPCSERVERSOAPMANAGERSERVICE_EXCEPTION!= null) {
            throw RPCSERVERSOAPMANAGERSERVICE_EXCEPTION;
        }
        return RPCSERVERSOAPMANAGERSERVICE_WSDL_LOCATION;
    }

}
