
package co.igb.transportws.client.coordinadora.ags;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 */
@WebService(name = "RpcServerSoapManagerPort", targetNamespace = "https://sandbox.coordinadora.com/ags/1.5/server.php")
@XmlSeeAlso({
        ObjectFactory.class
})
public interface RpcServerSoapManagerPort {


    /**
     * Departamentos
     *
     * @param p
     * @return returns https.sandbox_coordinadora_com.ags._1_5.server.ArrayOfCotizadorDepartamentosout
     */
    @WebMethod(operationName = "Cotizador_departamentos", action = "https://sandbox.coordinadora.com/ags/1.5/server.php#Cotizador_departamentos")
    @WebResult(name = "Cotizador_departamentosResult", targetNamespace = "")
    @RequestWrapper(localName = "Cotizador_departamentos", targetNamespace = "https://sandbox.coordinadora.com/ags/1.5/server.php", className = "https.sandbox_coordinadora_com.ags._1_5.server.CotizadorDepartamentos")
    @ResponseWrapper(localName = "Cotizador_departamentosResponse", targetNamespace = "https://sandbox.coordinadora.com/ags/1.5/server.php", className = "https.sandbox_coordinadora_com.ags._1_5.server.CotizadorDepartamentosResponse")
    public ArrayOfCotizadorDepartamentosout cotizadorDepartamentos(
            @WebParam(name = "p", targetNamespace = "")
                    TypeVoid p);

    /**
     * Ciudades cubiertas por Coordinadora, esta informaci�n se debe actualizar a diario.
     *
     * @param p
     * @return returns https.sandbox_coordinadora_com.ags._1_5.server.ArrayOfCotizadorCiudadesout
     */
    @WebMethod(operationName = "Cotizador_ciudades", action = "https://sandbox.coordinadora.com/ags/1.5/server.php#Cotizador_ciudades")
    @WebResult(name = "Cotizador_ciudadesResult", targetNamespace = "")
    @RequestWrapper(localName = "Cotizador_ciudades", targetNamespace = "https://sandbox.coordinadora.com/ags/1.5/server.php", className = "https.sandbox_coordinadora_com.ags._1_5.server.CotizadorCiudades")
    @ResponseWrapper(localName = "Cotizador_ciudadesResponse", targetNamespace = "https://sandbox.coordinadora.com/ags/1.5/server.php", className = "https.sandbox_coordinadora_com.ags._1_5.server.CotizadorCiudadesResponse")
    public ArrayOfCotizadorCiudadesout cotizadorCiudades(
            @WebParam(name = "p", targetNamespace = "")
                    TypeVoid p);

    /**
     * Cotizar de envios
     *
     * @param p
     * @return returns https.sandbox_coordinadora_com.ags._1_5.server.CotizadorCotizarOut
     */
    @WebMethod(operationName = "Cotizador_cotizar", action = "https://sandbox.coordinadora.com/ags/1.5/server.php#Cotizador_cotizar")
    @WebResult(name = "Cotizador_cotizarResult", targetNamespace = "")
    @RequestWrapper(localName = "Cotizador_cotizar", targetNamespace = "https://sandbox.coordinadora.com/ags/1.5/server.php", className = "https.sandbox_coordinadora_com.ags._1_5.server.CotizadorCotizar")
    @ResponseWrapper(localName = "Cotizador_cotizarResponse", targetNamespace = "https://sandbox.coordinadora.com/ags/1.5/server.php", className = "https.sandbox_coordinadora_com.ags._1_5.server.CotizadorCotizarResponse")
    public CotizadorCotizarOut cotizadorCotizar(
            @WebParam(name = "p", targetNamespace = "")
                    CotizadorCotizarIn p);

    /**
     * Cotizar de envios
     *
     * @param p
     * @return returns https.sandbox_coordinadora_com.ags._1_5.server.CotizadorCotizarInterOut
     */
    @WebMethod(operationName = "Cotizador_cotizarInter", action = "https://sandbox.coordinadora.com/ags/1.5/server.php#Cotizador_cotizarInter")
    @WebResult(name = "Cotizador_cotizarInterResult", targetNamespace = "")
    @RequestWrapper(localName = "Cotizador_cotizarInter", targetNamespace = "https://sandbox.coordinadora.com/ags/1.5/server.php", className = "https.sandbox_coordinadora_com.ags._1_5.server.CotizadorCotizarInter")
    @ResponseWrapper(localName = "Cotizador_cotizarInterResponse", targetNamespace = "https://sandbox.coordinadora.com/ags/1.5/server.php", className = "https.sandbox_coordinadora_com.ags._1_5.server.CotizadorCotizarInterResponse")
    public CotizadorCotizarInterOut cotizadorCotizarInter(
            @WebParam(name = "p", targetNamespace = "")
                    CotizadorCotizarInterIn p);

    /**
     * Reportar la novedad de una guia.
     *
     * @param p
     * @return returns https.sandbox_coordinadora_com.ags._1_5.server.GuiasReportarNovedadOut
     */
    @WebMethod(operationName = "Guias_reportarNovedad", action = "https://sandbox.coordinadora.com/ags/1.5/server.php#Guias_reportarNovedad")
    @WebResult(name = "Guias_reportarNovedadResult", targetNamespace = "")
    @RequestWrapper(localName = "Guias_reportarNovedad", targetNamespace = "https://sandbox.coordinadora.com/ags/1.5/server.php", className = "https.sandbox_coordinadora_com.ags._1_5.server.GuiasReportarNovedad")
    @ResponseWrapper(localName = "Guias_reportarNovedadResponse", targetNamespace = "https://sandbox.coordinadora.com/ags/1.5/server.php", className = "https.sandbox_coordinadora_com.ags._1_5.server.GuiasReportarNovedadResponse")
    public GuiasReportarNovedadOut guiasReportarNovedad(
            @WebParam(name = "p", targetNamespace = "")
                    GuiasReportarNovedadIn p);

    /**
     * Informe Negocios
     *
     * @param p
     * @return returns https.sandbox_coordinadora_com.ags._1_5.server.ArrayOfInformesNegociosout
     */
    @WebMethod(operationName = "Informes_negocios", action = "https://sandbox.coordinadora.com/ags/1.5/server.php#Informes_negocios")
    @WebResult(name = "Informes_negociosResult", targetNamespace = "")
    @RequestWrapper(localName = "Informes_negocios", targetNamespace = "https://sandbox.coordinadora.com/ags/1.5/server.php", className = "https.sandbox_coordinadora_com.ags._1_5.server.InformesNegocios")
    @ResponseWrapper(localName = "Informes_negociosResponse", targetNamespace = "https://sandbox.coordinadora.com/ags/1.5/server.php", className = "https.sandbox_coordinadora_com.ags._1_5.server.InformesNegociosResponse")
    public ArrayOfInformesNegociosout informesNegocios(
            @WebParam(name = "p", targetNamespace = "")
                    InformesNegociosIn p);

    /**
     * @param p
     * @return returns https.sandbox_coordinadora_com.ags._1_5.server.ArrayOfRecaudosOut
     */
    @WebMethod(operationName = "Recaudos_consultar", action = "https://sandbox.coordinadora.com/ags/1.5/server.php#Recaudos_consultar")
    @WebResult(name = "Recaudos_consultarResult", targetNamespace = "")
    @RequestWrapper(localName = "Recaudos_consultar", targetNamespace = "https://sandbox.coordinadora.com/ags/1.5/server.php", className = "https.sandbox_coordinadora_com.ags._1_5.server.RecaudosConsultar")
    @ResponseWrapper(localName = "Recaudos_consultarResponse", targetNamespace = "https://sandbox.coordinadora.com/ags/1.5/server.php", className = "https.sandbox_coordinadora_com.ags._1_5.server.RecaudosConsultarResponse")
    public ArrayOfRecaudosOut recaudosConsultar(
            @WebParam(name = "p", targetNamespace = "")
                    RecaudosIn p);

    /**
     * Consulta de ciudades autorizadas como destino
     * Excepciones: 10 -> Ya existe una recogida programada.
     *
     * @param p
     * @return returns https.sandbox_coordinadora_com.ags._1_5.server.RecogidasSolicitarOut
     */
    @WebMethod(operationName = "Recogidas_programar", action = "https://sandbox.coordinadora.com/ags/1.5/server.php#Recogidas_programar")
    @WebResult(name = "Recogidas_programarResult", targetNamespace = "")
    @RequestWrapper(localName = "Recogidas_programar", targetNamespace = "https://sandbox.coordinadora.com/ags/1.5/server.php", className = "https.sandbox_coordinadora_com.ags._1_5.server.RecogidasProgramar")
    @ResponseWrapper(localName = "Recogidas_programarResponse", targetNamespace = "https://sandbox.coordinadora.com/ags/1.5/server.php", className = "https.sandbox_coordinadora_com.ags._1_5.server.RecogidasProgramarResponse")
    public RecogidasSolicitarOut recogidasProgramar(
            @WebParam(name = "p", targetNamespace = "")
                    RecogidasSolicitarIn p);

    /**
     * Consulta de ciudades autorizadas como destino
     * Excepciones: 10 -> Ya existe una recogida programada.
     *
     * @param p
     * @return returns https.sandbox_coordinadora_com.ags._1_5.server.RecogidasSolicitarAlternaOut
     */
    @WebMethod(operationName = "Recogidas_programarAlterna", action = "https://sandbox.coordinadora.com/ags/1.5/server.php#Recogidas_programarAlterna")
    @WebResult(name = "Recogidas_programarAlternaResult", targetNamespace = "")
    @RequestWrapper(localName = "Recogidas_programarAlterna", targetNamespace = "https://sandbox.coordinadora.com/ags/1.5/server.php", className = "https.sandbox_coordinadora_com.ags._1_5.server.RecogidasProgramarAlterna")
    @ResponseWrapper(localName = "Recogidas_programarAlternaResponse", targetNamespace = "https://sandbox.coordinadora.com/ags/1.5/server.php", className = "https.sandbox_coordinadora_com.ags._1_5.server.RecogidasProgramarAlternaResponse")
    public RecogidasSolicitarAlternaOut recogidasProgramarAlterna(
            @WebParam(name = "p", targetNamespace = "")
                    RecogidasSolicitarAlternaIn p);

    /**
     * El listado de posibles estados son:
     * 1=ASIGNADA
     * 2=EFECTIVA
     * 3=CANCELADA
     * 4=APLAZADA
     *
     * @param p
     * @return returns https.sandbox_coordinadora_com.ags._1_5.server.RecogidasSeguimientoOut
     */
    @WebMethod(operationName = "Recogidas_seguimiento", action = "https://sandbox.coordinadora.com/ags/1.5/server.php#Recogidas_seguimiento")
    @WebResult(name = "Recogidas_seguimientoResult", targetNamespace = "")
    @RequestWrapper(localName = "Recogidas_seguimiento", targetNamespace = "https://sandbox.coordinadora.com/ags/1.5/server.php", className = "https.sandbox_coordinadora_com.ags._1_5.server.RecogidasSeguimiento")
    @ResponseWrapper(localName = "Recogidas_seguimientoResponse", targetNamespace = "https://sandbox.coordinadora.com/ags/1.5/server.php", className = "https.sandbox_coordinadora_com.ags._1_5.server.RecogidasSeguimientoResponse")
    public RecogidasSeguimientoOut recogidasSeguimiento(
            @WebParam(name = "p", targetNamespace = "")
                    RecogidasSeguimientoIn p);

    /**
     * El listado de posibles estados son:
     * 1=ASIGNADA
     * 2=EFECTIVA
     * 3=CANCELADA
     * 4=APLAZADA
     *
     * @param p
     * @return returns https.sandbox_coordinadora_com.ags._1_5.server.RecogidaSeguimientoExtOut
     */
    @WebMethod(operationName = "Recogidas_seguimientoExt", action = "https://sandbox.coordinadora.com/ags/1.5/server.php#Recogidas_seguimientoExt")
    @WebResult(name = "Recogidas_seguimientoExtResult", targetNamespace = "")
    @RequestWrapper(localName = "Recogidas_seguimientoExt", targetNamespace = "https://sandbox.coordinadora.com/ags/1.5/server.php", className = "https.sandbox_coordinadora_com.ags._1_5.server.RecogidasSeguimientoExt")
    @ResponseWrapper(localName = "Recogidas_seguimientoExtResponse", targetNamespace = "https://sandbox.coordinadora.com/ags/1.5/server.php", className = "https.sandbox_coordinadora_com.ags._1_5.server.RecogidasSeguimientoExtResponse")
    public RecogidaSeguimientoExtOut recogidasSeguimientoExt(
            @WebParam(name = "p", targetNamespace = "")
                    RecogidasSeguimientoIn p);

    /**
     * @param Recogidas_SeguimientoPorFechaIn
     * @param p
     * @return returns https.sandbox_coordinadora_com.ags._1_5.server.ArrayOfRecogidasSeguimientoporfechaout
     */
    @WebMethod(operationName = "Recogidas_seguimientoPorFecha", action = "https://sandbox.coordinadora.com/ags/1.5/server.php#Recogidas_seguimientoPorFecha")
    @WebResult(name = "Recogidas_seguimientoPorFechaResult", targetNamespace = "")
    @RequestWrapper(localName = "Recogidas_seguimientoPorFecha", targetNamespace = "https://sandbox.coordinadora.com/ags/1.5/server.php", className = "https.sandbox_coordinadora_com.ags._1_5.server.RecogidasSeguimientoPorFecha")
    @ResponseWrapper(localName = "Recogidas_seguimientoPorFechaResponse", targetNamespace = "https://sandbox.coordinadora.com/ags/1.5/server.php", className = "https.sandbox_coordinadora_com.ags._1_5.server.RecogidasSeguimientoPorFechaResponse")
    public ArrayOfRecogidasSeguimientoporfechaout recogidasSeguimientoPorFecha(
            @WebParam(name = "p", targetNamespace = "")
                    RecogidasSeguimientoPorFechaIn p);

    /**
     * El listado de posibles estados son:
     * 1=ASIGNADA
     * 2=EFECTIVA
     * 3=CANCELADA
     * 4=APLAZADA
     *
     * @param p
     * @return returns https.sandbox_coordinadora_com.ags._1_5.server.ArrayOfRecogidaSeguimientoextout
     */
    @WebMethod(operationName = "Recogidas_seguimientoFCDetalladoPorReferencia", action = "https://sandbox.coordinadora.com/ags/1.5/server.php#Recogidas_seguimientoFCDetalladoPorReferencia")
    @WebResult(name = "Recogidas_seguimientoFCDetalladoPorReferenciaResult", targetNamespace = "")
    @RequestWrapper(localName = "Recogidas_seguimientoFCDetalladoPorReferencia", targetNamespace = "https://sandbox.coordinadora.com/ags/1.5/server.php", className = "https.sandbox_coordinadora_com.ags._1_5.server.RecogidasSeguimientoFCDetalladoPorReferencia")
    @ResponseWrapper(localName = "Recogidas_seguimientoFCDetalladoPorReferenciaResponse", targetNamespace = "https://sandbox.coordinadora.com/ags/1.5/server.php", className = "https.sandbox_coordinadora_com.ags._1_5.server.RecogidasSeguimientoFCDetalladoPorReferenciaResponse")
    public ArrayOfRecogidaSeguimientoextout recogidasSeguimientoFCDetalladoPorReferencia(
            @WebParam(name = "p", targetNamespace = "")
                    RecogidasSeguimientoReferenciaIn p);

    /**
     * Servicio web para generaci�n r�tulos en PDF (base 64) a partir de unos filtros de informaci�n.
     *
     * @param p
     * @return returns https.sandbox_coordinadora_com.ags._1_5.server.RotulosCmOut
     */
    @WebMethod(operationName = "Rotulos_generar", action = "https://sandbox.coordinadora.com/ags/1.5/server.php#Rotulos_generar")
    @WebResult(name = "Rotulos_generarResult", targetNamespace = "")
    @RequestWrapper(localName = "Rotulos_generar", targetNamespace = "https://sandbox.coordinadora.com/ags/1.5/server.php", className = "https.sandbox_coordinadora_com.ags._1_5.server.RotulosGenerar")
    @ResponseWrapper(localName = "Rotulos_generarResponse", targetNamespace = "https://sandbox.coordinadora.com/ags/1.5/server.php", className = "https.sandbox_coordinadora_com.ags._1_5.server.RotulosGenerarResponse")
    public RotulosCmOut rotulosGenerar(
            @WebParam(name = "p", targetNamespace = "")
                    RotulosGenerarIn p);

    /**
     * Servicio web para generaci�n r�tulos RD en PDF (base 64) a partir de unos filtros de informaci�n.
     *
     * @param p
     * @return returns https.sandbox_coordinadora_com.ags._1_5.server.RotulosCmOut
     */
    @WebMethod(operationName = "Rotulos_generarRd", action = "https://sandbox.coordinadora.com/ags/1.5/server.php#Rotulos_generarRd")
    @WebResult(name = "Rotulos_generarRdResult", targetNamespace = "")
    @RequestWrapper(localName = "Rotulos_generarRd", targetNamespace = "https://sandbox.coordinadora.com/ags/1.5/server.php", className = "https.sandbox_coordinadora_com.ags._1_5.server.RotulosGenerarRd")
    @ResponseWrapper(localName = "Rotulos_generarRdResponse", targetNamespace = "https://sandbox.coordinadora.com/ags/1.5/server.php", className = "https.sandbox_coordinadora_com.ags._1_5.server.RotulosGenerarRdResponse")
    public RotulosCmOut rotulosGenerarRd(
            @WebParam(name = "p", targetNamespace = "")
                    RotulosGenerarIn p);

    /**
     * Servicio web para generar Datos que sirvan de integraci�n con los clientes.
     *
     * @param p
     * @return returns https.sandbox_coordinadora_com.ags._1_5.server.ArrayOfRotulosIntegracionout
     */
    @WebMethod(operationName = "Rotulos_integracion", action = "https://sandbox.coordinadora.com/ags/1.5/server.php#Rotulos_integracion")
    @WebResult(name = "Rotulos_integracionResult", targetNamespace = "")
    @RequestWrapper(localName = "Rotulos_integracion", targetNamespace = "https://sandbox.coordinadora.com/ags/1.5/server.php", className = "https.sandbox_coordinadora_com.ags._1_5.server.RotulosIntegracion")
    @ResponseWrapper(localName = "Rotulos_integracionResponse", targetNamespace = "https://sandbox.coordinadora.com/ags/1.5/server.php", className = "https.sandbox_coordinadora_com.ags._1_5.server.RotulosIntegracionResponse")
    public ArrayOfRotulosIntegracionout rotulosIntegracion(
            @WebParam(name = "p", targetNamespace = "")
                    RotulosIntegracionIn p);

    /**
     * Servicio web para generaci�n r�tulos en PDF (base 64) sin nig�n filtro
     *
     * @param p
     * @return returns https.sandbox_coordinadora_com.ags._1_5.server.RotulosCmOut
     */
    @WebMethod(operationName = "Rotulos_imprimirCm", action = "https://sandbox.coordinadora.com/ags/1.5/server.php#Rotulos_imprimirCm")
    @WebResult(name = "Rotulos_imprimirCmResult", targetNamespace = "")
    @RequestWrapper(localName = "Rotulos_imprimirCm", targetNamespace = "https://sandbox.coordinadora.com/ags/1.5/server.php", className = "https.sandbox_coordinadora_com.ags._1_5.server.RotulosImprimirCm")
    @ResponseWrapper(localName = "Rotulos_imprimirCmResponse", targetNamespace = "https://sandbox.coordinadora.com/ags/1.5/server.php", className = "https.sandbox_coordinadora_com.ags._1_5.server.RotulosImprimirCmResponse")
    public RotulosCmOut rotulosImprimirCm(
            @WebParam(name = "p", targetNamespace = "")
                    RotulosImprimirCmIn p);

    /**
     * Servicio web para generar Datos o PDF de una etiqueta sin guia.
     *
     * @param p
     * @return returns https.sandbox_coordinadora_com.ags._1_5.server.RotulosPrevioOut
     */
    @WebMethod(operationName = "Rotulos_previo", action = "https://sandbox.coordinadora.com/ags/1.5/server.php#Rotulos_previo")
    @WebResult(name = "Rotulos_previoResult", targetNamespace = "")
    @RequestWrapper(localName = "Rotulos_previo", targetNamespace = "https://sandbox.coordinadora.com/ags/1.5/server.php", className = "https.sandbox_coordinadora_com.ags._1_5.server.RotulosPrevio")
    @ResponseWrapper(localName = "Rotulos_previoResponse", targetNamespace = "https://sandbox.coordinadora.com/ags/1.5/server.php", className = "https.sandbox_coordinadora_com.ags._1_5.server.RotulosPrevioResponse")
    public RotulosPrevioOut rotulosPrevio(
            @WebParam(name = "p", targetNamespace = "")
                    RotulosPrevioIn p);

    /**
     * Servicio web para generar Datos o PDF de una etiqueta RD sin guia.
     *
     * @param p
     * @return returns https.sandbox_coordinadora_com.ags._1_5.server.RotulosPrevioRDOut
     */
    @WebMethod(operationName = "Rotulos_previoRD", action = "https://sandbox.coordinadora.com/ags/1.5/server.php#Rotulos_previoRD")
    @WebResult(name = "Rotulos_previoRDResult", targetNamespace = "")
    @RequestWrapper(localName = "Rotulos_previoRD", targetNamespace = "https://sandbox.coordinadora.com/ags/1.5/server.php", className = "https.sandbox_coordinadora_com.ags._1_5.server.RotulosPrevioRD")
    @ResponseWrapper(localName = "Rotulos_previoRDResponse", targetNamespace = "https://sandbox.coordinadora.com/ags/1.5/server.php", className = "https.sandbox_coordinadora_com.ags._1_5.server.RotulosPrevioRDResponse")
    public RotulosPrevioRDOut rotulosPrevioRD(
            @WebParam(name = "p", targetNamespace = "")
                    RotulosPrevioRDIn p);

    /**
     * Consultar el estado de una guia
     *
     * @param p
     * @return returns https.sandbox_coordinadora_com.ags._1_5.server.SeguimientoSimpleOut
     */
    @WebMethod(operationName = "Seguimiento_simple", action = "https://sandbox.coordinadora.com/ags/1.5/server.php#Seguimiento_simple")
    @WebResult(name = "Seguimiento_simpleResult", targetNamespace = "")
    @RequestWrapper(localName = "Seguimiento_simple", targetNamespace = "https://sandbox.coordinadora.com/ags/1.5/server.php", className = "https.sandbox_coordinadora_com.ags._1_5.server.SeguimientoSimple")
    @ResponseWrapper(localName = "Seguimiento_simpleResponse", targetNamespace = "https://sandbox.coordinadora.com/ags/1.5/server.php", className = "https.sandbox_coordinadora_com.ags._1_5.server.SeguimientoSimpleResponse")
    public SeguimientoSimpleOut seguimientoSimple(
            @WebParam(name = "p", targetNamespace = "")
                    SeguimientoSimpleIn p);

    /**
     * Seguimiento detallado
     *
     * @param p
     * @return returns https.sandbox_coordinadora_com.ags._1_5.server.SeguimientoDetalladoOut
     */
    @WebMethod(operationName = "Seguimiento_detallado", action = "https://sandbox.coordinadora.com/ags/1.5/server.php#Seguimiento_detallado")
    @WebResult(name = "Seguimiento_detalladoResult", targetNamespace = "")
    @RequestWrapper(localName = "Seguimiento_detallado", targetNamespace = "https://sandbox.coordinadora.com/ags/1.5/server.php", className = "https.sandbox_coordinadora_com.ags._1_5.server.SeguimientoDetallado")
    @ResponseWrapper(localName = "Seguimiento_detalladoResponse", targetNamespace = "https://sandbox.coordinadora.com/ags/1.5/server.php", className = "https.sandbox_coordinadora_com.ags._1_5.server.SeguimientoDetalladoResponse")
    public SeguimientoDetalladoOut seguimientoDetallado(
            @WebParam(name = "p", targetNamespace = "")
                    SeguimientoDetalladoIn p);

    /**
     * Consultar guias levantadas en una fecha determinada
     *
     * @param p
     * @return returns https.sandbox_coordinadora_com.ags._1_5.server.ConsultarLevantadasOut
     */
    @WebMethod(operationName = "Seguimiento_consultarLevantadas", action = "https://sandbox.coordinadora.com/ags/1.5/server.php#Seguimiento_consultarLevantadas")
    @WebResult(name = "Seguimiento_consultarLevantadasResult", targetNamespace = "")
    @RequestWrapper(localName = "Seguimiento_consultarLevantadas", targetNamespace = "https://sandbox.coordinadora.com/ags/1.5/server.php", className = "https.sandbox_coordinadora_com.ags._1_5.server.SeguimientoConsultarLevantadas")
    @ResponseWrapper(localName = "Seguimiento_consultarLevantadasResponse", targetNamespace = "https://sandbox.coordinadora.com/ags/1.5/server.php", className = "https.sandbox_coordinadora_com.ags._1_5.server.SeguimientoConsultarLevantadasResponse")
    public ConsultarLevantadasOut seguimientoConsultarLevantadas(
            @WebParam(name = "p", targetNamespace = "")
                    ConsultarLevantadasIn p);
}