
package co.igb.apiSoul.client.wsClientesBodegas;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.6-1b01 
 * Generated source version: 2.2
 * 
 */
@WebService(name = "wsClientesBodegasHttpGet", targetNamespace = "http://tempuri.org/")
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
@XmlSeeAlso({
    ObjectFactory.class
})
public interface WsClientesBodegasHttpGet {


    /**
     * 
     * @param pContrasena
     * @param pUsuario
     * @return
     *     returns co.igb.apiSoul.client.wsClientesBodegas.RespConsultaInventario
     */
    @WebMethod(operationName = "ConsultaInventario")
    @WebResult(name = "RespConsultaInventario", targetNamespace = "http://tempuri.org/", partName = "Body")
    public RespConsultaInventario consultaInventario(
        @WebParam(name = "string", targetNamespace = "http://www.w3.org/2001/XMLSchema", partName = "pUsuario")
        String pUsuario,
        @WebParam(name = "string", targetNamespace = "http://www.w3.org/2001/XMLSchema", partName = "pContrasena")
        String pContrasena);

    /**
     * 
     * @param pContrasena
     * @param pUsuario
     * @return
     *     returns co.igb.apiSoul.client.wsClientesBodegas.RespConsultaInventarioBodega
     */
    @WebMethod(operationName = "ConsultaInventarioBodega")
    @WebResult(name = "RespConsultaInventarioBodega", targetNamespace = "http://tempuri.org/", partName = "Body")
    public RespConsultaInventarioBodega consultaInventarioBodega(
        @WebParam(name = "string", targetNamespace = "http://www.w3.org/2001/XMLSchema", partName = "pUsuario")
        String pUsuario,
        @WebParam(name = "string", targetNamespace = "http://www.w3.org/2001/XMLSchema", partName = "pContrasena")
        String pContrasena);

    /**
     * 
     * @param pContrasena
     * @param pDocTransporte
     * @param pUsuario
     * @return
     *     returns co.igb.apiSoul.client.wsClientesBodegas.RespConsultaConteo
     */
    @WebMethod(operationName = "ConsultaConteosxDocTransporte")
    @WebResult(name = "RespConsultaConteo", targetNamespace = "http://tempuri.org/", partName = "Body")
    public RespConsultaConteo consultaConteosxDocTransporte(
        @WebParam(name = "string", targetNamespace = "http://www.w3.org/2001/XMLSchema", partName = "pUsuario")
        String pUsuario,
        @WebParam(name = "string", targetNamespace = "http://www.w3.org/2001/XMLSchema", partName = "pContrasena")
        String pContrasena,
        @WebParam(name = "string", targetNamespace = "http://www.w3.org/2001/XMLSchema", partName = "pDocTransporte")
        String pDocTransporte);

    /**
     * 
     * @param pTipoConteo
     * @param pContrasena
     * @param pNroFactura
     * @param pUsuario
     * @return
     *     returns co.igb.apiSoul.client.wsClientesBodegas.RespReporteConteo
     */
    @WebMethod(operationName = "ReporteConteo")
    @WebResult(name = "RespReporteConteo", targetNamespace = "http://tempuri.org/", partName = "Body")
    public RespReporteConteo reporteConteo(
        @WebParam(name = "string", targetNamespace = "http://www.w3.org/2001/XMLSchema", partName = "pUsuario")
        String pUsuario,
        @WebParam(name = "string", targetNamespace = "http://www.w3.org/2001/XMLSchema", partName = "pContrasena")
        String pContrasena,
        @WebParam(name = "string", targetNamespace = "http://www.w3.org/2001/XMLSchema", partName = "pNroFactura")
        String pNroFactura,
        @WebParam(name = "string", targetNamespace = "http://www.w3.org/2001/XMLSchema", partName = "pTipoConteo")
        String pTipoConteo);

    /**
     * 
     * @param usuario
     * @param consecutivoSalida
     * @param contrasena
     * @return
     *     returns co.igb.apiSoul.client.wsClientesBodegas.RespConsultarEstadoPaquete
     */
    @WebMethod(operationName = "ConsultarEstadoPaquete")
    @WebResult(name = "RespConsultarEstadoPaquete", targetNamespace = "http://tempuri.org/", partName = "Body")
    public RespConsultarEstadoPaquete consultarEstadoPaquete(
        @WebParam(name = "string", targetNamespace = "http://www.w3.org/2001/XMLSchema", partName = "Usuario")
        String usuario,
        @WebParam(name = "string", targetNamespace = "http://www.w3.org/2001/XMLSchema", partName = "Contrasena")
        String contrasena,
        @WebParam(name = "string", targetNamespace = "http://www.w3.org/2001/XMLSchema", partName = "ConsecutivoSalida")
        String consecutivoSalida);

    /**
     * 
     * @param usuario
     * @param contrasena
     * @param consecutivoCaja
     * @return
     *     returns co.igb.apiSoul.client.wsClientesBodegas.RespConsultarEstadoPaquete
     */
    @WebMethod(operationName = "ConsultarEstadoPaquetexCaja")
    @WebResult(name = "RespConsultarEstadoPaquete", targetNamespace = "http://tempuri.org/", partName = "Body")
    public RespConsultarEstadoPaquete consultarEstadoPaquetexCaja(
        @WebParam(name = "string", targetNamespace = "http://www.w3.org/2001/XMLSchema", partName = "Usuario")
        String usuario,
        @WebParam(name = "string", targetNamespace = "http://www.w3.org/2001/XMLSchema", partName = "Contrasena")
        String contrasena,
        @WebParam(name = "string", targetNamespace = "http://www.w3.org/2001/XMLSchema", partName = "ConsecutivoCaja")
        String consecutivoCaja);

    /**
     * 
     * @param tramitada
     * @param usuario
     * @param ordenCompra
     * @param numeroBp
     * @param detalleOrden
     * @param fechaOrdenHasta
     * @param consecutivoSalida
     * @param contrasena
     * @param fechaOrdenDesde
     * @return
     *     returns co.igb.apiSoul.client.wsClientesBodegas.RespSalidasEverfit
     */
    @WebMethod(operationName = "ConsultarOrdenesSalidaEverfit")
    @WebResult(name = "RespSalidasEverfit", targetNamespace = "http://tempuri.org/", partName = "Body")
    public RespSalidasEverfit consultarOrdenesSalidaEverfit(
        @WebParam(name = "string", targetNamespace = "http://www.w3.org/2001/XMLSchema", partName = "usuario")
        String usuario,
        @WebParam(name = "string", targetNamespace = "http://www.w3.org/2001/XMLSchema", partName = "contrasena")
        String contrasena,
        @WebParam(name = "string", targetNamespace = "http://www.w3.org/2001/XMLSchema", partName = "fechaOrdenDesde")
        String fechaOrdenDesde,
        @WebParam(name = "string", targetNamespace = "http://www.w3.org/2001/XMLSchema", partName = "fechaOrdenHasta")
        String fechaOrdenHasta,
        @WebParam(name = "string", targetNamespace = "http://www.w3.org/2001/XMLSchema", partName = "numeroBp")
        String numeroBp,
        @WebParam(name = "string", targetNamespace = "http://www.w3.org/2001/XMLSchema", partName = "consecutivoSalida")
        String consecutivoSalida,
        @WebParam(name = "string", targetNamespace = "http://www.w3.org/2001/XMLSchema", partName = "ordenCompra")
        String ordenCompra,
        @WebParam(name = "string", targetNamespace = "http://www.w3.org/2001/XMLSchema", partName = "detalleOrden")
        String detalleOrden,
        @WebParam(name = "string", targetNamespace = "http://www.w3.org/2001/XMLSchema", partName = "tramitada")
        String tramitada);

    /**
     * 
     * @param usuario
     * @param nroPedido
     * @param contrasena
     * @return
     *     returns co.igb.apiSoul.client.wsClientesBodegas.RespConsultarPaquetesxPedido
     */
    @WebMethod(operationName = "ConsultarPaquetesxPedido")
    @WebResult(name = "RespConsultarPaquetesxPedido", targetNamespace = "http://tempuri.org/", partName = "Body")
    public RespConsultarPaquetesxPedido consultarPaquetesxPedido(
        @WebParam(name = "string", targetNamespace = "http://www.w3.org/2001/XMLSchema", partName = "usuario")
        String usuario,
        @WebParam(name = "string", targetNamespace = "http://www.w3.org/2001/XMLSchema", partName = "contrasena")
        String contrasena,
        @WebParam(name = "string", targetNamespace = "http://www.w3.org/2001/XMLSchema", partName = "nroPedido")
        String nroPedido);

    /**
     * 
     * @param usuario
     * @param nroPedido
     * @param contrasena
     * @return
     *     returns co.igb.apiSoul.client.wsClientesBodegas.RespConsultarGuiasxPedido
     */
    @WebMethod(operationName = "ConsultarGuiasxPedido")
    @WebResult(name = "RespConsultarGuiasxPedido", targetNamespace = "http://tempuri.org/", partName = "Body")
    public RespConsultarGuiasxPedido consultarGuiasxPedido(
        @WebParam(name = "string", targetNamespace = "http://www.w3.org/2001/XMLSchema", partName = "usuario")
        String usuario,
        @WebParam(name = "string", targetNamespace = "http://www.w3.org/2001/XMLSchema", partName = "contrasena")
        String contrasena,
        @WebParam(name = "string", targetNamespace = "http://www.w3.org/2001/XMLSchema", partName = "nroPedido")
        String nroPedido);

}
