
package co.igb.transportws.client.coordinadora.agw;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 */
@WebService(name = "JRpcServerSoapManagerPort", targetNamespace = "https://sandbox.coordinadora.com/agw/ws/guias/1.6/server.php")
@SOAPBinding(style = SOAPBinding.Style.RPC)
@XmlSeeAlso({
        ObjectFactory.class
})
public interface JRpcServerSoapManagerPort {


    /**
     * Generar gu�a
     *
     * @param p
     * @return returns https.sandbox_coordinadora_com.agw.ws.guias._1_6.server.AgwTypeGenerarGuiaOut
     */
    @WebMethod(operationName = "Guias_generarGuia", action = "https://sandbox.coordinadora.com/agw/ws/guias/1.6/server.php#Guias_generarGuia")
    @WebResult(partName = "return")
    public AgwTypeGenerarGuiaOut guiasGenerarGuia(
            @WebParam(name = "p", partName = "p")
                    AgwTypeGenerarGuiaIn p);

    /**
     * Anular gu�a
     *
     * @param p
     * @return returns boolean
     */
    @WebMethod(operationName = "Guias_anularGuia", action = "https://sandbox.coordinadora.com/agw/ws/guias/1.6/server.php#Guias_anularGuia")
    @WebResult(partName = "return")
    public boolean guiasAnularGuia(
            @WebParam(name = "p", partName = "p")
                    AgwTypeAnularGuiaIn p);

    /**
     * M�todo que permite consultar los valores de liquidacion de la gu�a.
     *
     * @param p
     * @return returns https.sandbox_coordinadora_com.agw.ws.guias._1_6.server.AgwLiquidacionGuiaOut
     */
    @WebMethod(operationName = "Guias_liquidacionGuia", action = "https://sandbox.coordinadora.com/agw/ws/guias/1.6/server.php#Guias_liquidacionGuia")
    @WebResult(partName = "return")
    public AgwLiquidacionGuiaOut guiasLiquidacionGuia(
            @WebParam(name = "p", partName = "p")
                    AgwLiquidacionGuiaIn p);

    /**
     * Genera el despacho para un grupo de guias que se especifique.
     * Se genera un despacho por cada nit-div diferente que tengan las guias.
     * Puede retornar multiples registros.
     *
     * @param p
     * @return returns https.sandbox_coordinadora_com.agw.ws.guias._1_6.server.ArrayOfAgwTypeGenerarDespachoOut
     */
    @WebMethod(operationName = "Guias_generarDespacho", action = "https://sandbox.coordinadora.com/agw/ws/guias/1.6/server.php#Guias_generarDespacho")
    @WebResult(partName = "return")
    public ArrayOfAgwTypeGenerarDespachoOut guiasGenerarDespacho(
            @WebParam(name = "p", partName = "p")
                    AgwTypeGenerarDespachoIn p);

    /**
     * Genera el despacho para un grupo de identificadores de clientes con levante previo.
     * Se genera un despacho por cada id cliente diferente que tengan guias y levantes cargadas previamente.
     * Puede retornar multiples registros.
     *
     * @param p
     * @return returns https.sandbox_coordinadora_com.agw.ws.guias._1_6.server.ArrayOfAgwTypeGenerarDespachoBasicoOut
     */
    @WebMethod(operationName = "Guias_generarDespacharLevantePrevio", action = "https://sandbox.coordinadora.com/agw/ws/guias/1.6/server.php#Guias_generarDespacharLevantePrevio")
    @WebResult(partName = "return")
    public ArrayOfAgwTypeGenerarDespachoBasicoOut guiasGenerarDespacharLevantePrevio(
            @WebParam(name = "p", partName = "p")
                    AgwTypeGenerarDespachoLevantePrevioIn p);

    /**
     * Reimprimir guia
     *
     * @param p
     * @return returns https.sandbox_coordinadora_com.agw.ws.guias._1_6.server.AgwTypeReimprimirGuiaOut
     */
    @WebMethod(operationName = "Guias_reimprimirGuia", action = "https://sandbox.coordinadora.com/agw/ws/guias/1.6/server.php#Guias_reimprimirGuia")
    @WebResult(partName = "return")
    public AgwTypeReimprimirGuiaOut guiasReimprimirGuia(
            @WebParam(name = "p", partName = "p")
                    AgwTypeReimprimirGuiaIn p);

    /**
     * Reimprimir despacho
     *
     * @param p
     * @return returns https.sandbox_coordinadora_com.agw.ws.guias._1_6.server.AgwTypeReimprimirDespachoOut
     */
    @WebMethod(operationName = "Guias_reimprimirDespacho", action = "https://sandbox.coordinadora.com/agw/ws/guias/1.6/server.php#Guias_reimprimirDespacho")
    @WebResult(partName = "return")
    public AgwTypeReimprimirDespachoOut guiasReimprimirDespacho(
            @WebParam(name = "p", partName = "p")
                    AgwTypeReimprimirDespachoIn p);

    /**
     * Reimprimir despacho POS
     *
     * @param p
     * @return returns https.sandbox_coordinadora_com.agw.ws.guias._1_6.server.AgwTypeReimprimirDespachoPlanoOut
     */
    @WebMethod(operationName = "Guias_reimprimirDespachoPlano", action = "https://sandbox.coordinadora.com/agw/ws/guias/1.6/server.php#Guias_reimprimirDespachoPlano")
    @WebResult(partName = "return")
    public AgwTypeReimprimirDespachoPlanoOut guiasReimprimirDespachoPlano(
            @WebParam(name = "p", partName = "p")
                    AgwTypeReimprimirDespachoPlanoIn p);

    /**
     * Consultar despachos generados
     *
     * @param p
     * @return returns https.sandbox_coordinadora_com.agw.ws.guias._1_6.server.AgwTypeconsultarDespachosOut
     */
    @WebMethod(operationName = "Guias_consultarDespachos", action = "https://sandbox.coordinadora.com/agw/ws/guias/1.6/server.php#Guias_consultarDespachos")
    @WebResult(partName = "return")
    public AgwTypeconsultarDespachosOut guiasConsultarDespachos(
            @WebParam(name = "p", partName = "p")
                    AgwTypeconsultarDespachosIn p);

    /**
     * Consultar guia retorno RDFD
     *
     * @param p
     * @return returns https.sandbox_coordinadora_com.agw.ws.guias._1_6.server.AgwTypeConsultarRetornoRDFDOut
     */
    @WebMethod(operationName = "Guias_consultarRetornoRDFD", action = "https://sandbox.coordinadora.com/agw/ws/guias/1.6/server.php#Guias_consultarRetornoRDFD")
    @WebResult(partName = "return")
    public AgwTypeConsultarRetornoRDFDOut guiasConsultarRetornoRDFD(
            @WebParam(name = "p", partName = "p")
                    AgwTypeConsultarRetornoRDFDIn p);

    /**
     * Actualizar peso y volumen de guia retorno RDFD
     *
     * @param p
     * @return returns https.sandbox_coordinadora_com.agw.ws.guias._1_6.server.AgwTypeActualizarPesoVolumenRetornoRDFDOut
     */
    @WebMethod(operationName = "Guias_actualizarPesoVolumenRetornoRDFD", action = "https://sandbox.coordinadora.com/agw/ws/guias/1.6/server.php#Guias_actualizarPesoVolumenRetornoRDFD")
    @WebResult(partName = "return")
    public AgwTypeActualizarPesoVolumenRetornoRDFDOut guiasActualizarPesoVolumenRetornoRDFD(
            @WebParam(name = "p", partName = "p")
                    AgwTypeActualizarPesoVolumenRetornoRDFDIn p);

    /**
     * Generar despacho RDFD
     *
     * @param p
     * @return returns https.sandbox_coordinadora_com.agw.ws.guias._1_6.server.TypeVoid
     */
    @WebMethod(operationName = "Guias_generarDespachoRDFD", action = "https://sandbox.coordinadora.com/agw/ws/guias/1.6/server.php#Guias_generarDespachoRDFD")
    @WebResult(partName = "return")
    public TypeVoid guiasGenerarDespachoRDFD(
            @WebParam(name = "p", partName = "p")
                    AgwTypeGenerarDespachoRDFDIn p);

    /**
     * Rastrear guia
     *
     * @param p
     * @return returns https.sandbox_coordinadora_com.agw.ws.guias._1_6.server.ArrayOfAgwTypeRastreoSimpleOut
     */
    @WebMethod(operationName = "Guias_rastreoSimple", action = "https://sandbox.coordinadora.com/agw/ws/guias/1.6/server.php#Guias_rastreoSimple")
    @WebResult(partName = "return")
    public ArrayOfAgwTypeRastreoSimpleOut guiasRastreoSimple(
            @WebParam(name = "p", partName = "p")
                    AgwTypeRastreoSimpleIn p);

    /**
     * Rastrear guia
     *
     * @param p
     * @return returns https.sandbox_coordinadora_com.agw.ws.guias._1_6.server.ArrayOfAgwTypeRastreoExtendidoOut
     */
    @WebMethod(operationName = "Guias_rastreoExtendido", action = "https://sandbox.coordinadora.com/agw/ws/guias/1.6/server.php#Guias_rastreoExtendido")
    @WebResult(partName = "return")
    public ArrayOfAgwTypeRastreoExtendidoOut guiasRastreoExtendido(
            @WebParam(name = "p", partName = "p")
                    AgwTypeRastreoExtendidoIn p);

    /**
     * Devuelve las guias incluidas en un despacho
     *
     * @param p
     * @return returns https.sandbox_coordinadora_com.agw.ws.guias._1_6.server.AgwDetalleDespachoOut
     */
    @WebMethod(operationName = "Guias_detalleDespacho", action = "https://sandbox.coordinadora.com/agw/ws/guias/1.6/server.php#Guias_detalleDespacho")
    @WebResult(partName = "return")
    public AgwDetalleDespachoOut guiasDetalleDespacho(
            @WebParam(name = "p", partName = "p")
                    AgwDetalleDespachoIn p);

    /**
     * Devuelve el estado de un recaudo, se puede consultar por codigo_remision o por reference del recaudo
     *
     * @param p
     * @return returns https.sandbox_coordinadora_com.agw.ws.guias._1_6.server.AgwEstadoRecaudoOut
     */
    @WebMethod(operationName = "Guias_estadoRecaudo", action = "https://sandbox.coordinadora.com/agw/ws/guias/1.6/server.php#Guias_estadoRecaudo")
    @WebResult(partName = "return")
    public AgwEstadoRecaudoOut guiasEstadoRecaudo(
            @WebParam(name = "p", partName = "p")
                    AgwEstadoRecaudoIn p);

    /**
     * Ciudades activas al momento de la consultas.
     *
     * @param p
     * @return returns https.sandbox_coordinadora_com.agw.ws.guias._1_6.server.ArrayOfAgwCiudadesOut
     */
    @WebMethod(operationName = "Guias_ciudades", action = "https://sandbox.coordinadora.com/agw/ws/guias/1.6/server.php#Guias_ciudades")
    @WebResult(partName = "return")
    public ArrayOfAgwCiudadesOut guiasCiudades(
            @WebParam(name = "p", partName = "p")
                    AgwCiudadesIn p);

    /**
     * Ciudades disponibles
     *
     * @param p
     * @return returns https.sandbox_coordinadora_com.agw.ws.guias._1_6.server.ArrayOfAgwGenerarDespachoMovilOut
     */
    @WebMethod(operationName = "Guias_generarDespachoMovil", action = "https://sandbox.coordinadora.com/agw/ws/guias/1.6/server.php#Guias_generarDespachoMovil")
    @WebResult(partName = "return")
    public ArrayOfAgwGenerarDespachoMovilOut guiasGenerarDespachoMovil(
            @WebParam(name = "p", partName = "p")
                    AgwGenerarDespachoMovilIn p);

    /**
     * @param Agw_imprimirRotulosIn
     * @param p
     * @return returns https.sandbox_coordinadora_com.agw.ws.guias._1_6.server.AgwImprimirRotulosOut
     */
    @WebMethod(operationName = "Guias_imprimirRotulos", action = "https://sandbox.coordinadora.com/agw/ws/guias/1.6/server.php#Guias_imprimirRotulos")
    @WebResult(partName = "return")
    public AgwImprimirRotulosOut guiasImprimirRotulos(
            @WebParam(name = "p", partName = "p")
                    AgwImprimirRotulosIn p);

    /**
     * Reimprimir multiples guias
     *
     * @param p
     * @return returns https.sandbox_coordinadora_com.agw.ws.guias._1_6.server.AgwTypeReimprimirGuiasOut
     */
    @WebMethod(operationName = "Guias_reimprimirGuias", action = "https://sandbox.coordinadora.com/agw/ws/guias/1.6/server.php#Guias_reimprimirGuias")
    @WebResult(partName = "return")
    public AgwTypeReimprimirGuiasOut guiasReimprimirGuias(
            @WebParam(name = "p", partName = "p")
                    AgwTypeReimprimirGuiasIn p);

    /**
     * Generar gu�a Internacional
     *
     * @param p
     * @return returns https.sandbox_coordinadora_com.agw.ws.guias._1_6.server.AgwTypeGenerarGuiaInterOut
     */
    @WebMethod(operationName = "Guias_generarGuiaInter", action = "https://sandbox.coordinadora.com/agw/ws/guias/1.6/server.php#Guias_generarGuiaInter")
    @WebResult(partName = "return")
    public AgwTypeGenerarGuiaInterOut guiasGenerarGuiaInter(
            @WebParam(name = "p", partName = "p")
                    AgwTypeGenerarGuiaInterIn p);

    /**
     * Editar gu�a
     *
     * @param p
     * @return returns https.sandbox_coordinadora_com.agw.ws.guias._1_6.server.AgwTypeEditarGuiaOut
     */
    @WebMethod(operationName = "Guias_editarGuia", action = "https://sandbox.coordinadora.com/agw/ws/guias/1.6/server.php#Guias_editarGuia")
    @WebResult(partName = "return")
    public AgwTypeEditarGuiaOut guiasEditarGuia(
            @WebParam(name = "p", partName = "p")
                    AgwTypeEditarGuiaIn p);

    /**
     * Webservice para generar etiqueta previa, ya sea la data o el PDF en base 64
     *
     * @param p
     * @return returns https.sandbox_coordinadora_com.agw.ws.guias._1_6.server.AgwRotuloPrevioOut
     */
    @WebMethod(operationName = "Guias_rotuloPrevio", action = "https://sandbox.coordinadora.com/agw/ws/guias/1.6/server.php#Guias_rotuloPrevio")
    @WebResult(partName = "return")
    public AgwRotuloPrevioOut guiasRotuloPrevio(
            @WebParam(name = "p", partName = "p")
                    AgwRotuloPrevioIn p);

    /**
     * Webservice para generar etiqueta previa con RD, ya sea la data o el PDF en base 64
     *
     * @param p
     * @return returns https.sandbox_coordinadora_com.agw.ws.guias._1_6.server.AgwRotuloPrevioRDOut
     */
    @WebMethod(operationName = "Guias_rotuloPrevioRD", action = "https://sandbox.coordinadora.com/agw/ws/guias/1.6/server.php#Guias_rotuloPrevioRD")
    @WebResult(partName = "return")
    public AgwRotuloPrevioRDOut guiasRotuloPrevioRD(
            @WebParam(name = "p", partName = "p")
                    AgwRotuloPrevioRDIn p);

    /**
     * Crea una novedad en el sistema en el cual cuando soliciten un c�digo de unidad entrada, esta debe
     * imprimir la unidad de salida
     *
     * @param p
     * @return returns https.sandbox_coordinadora_com.agw.ws.guias._1_6.server.AgwTypeNovedadReetiquetadoOut
     */
    @WebMethod(operationName = "Guias_novedadReetiquetado", action = "https://sandbox.coordinadora.com/agw/ws/guias/1.6/server.php#Guias_novedadReetiquetado")
    @WebResult(partName = "return")
    public AgwTypeNovedadReetiquetadoOut guiasNovedadReetiquetado(
            @WebParam(name = "p", partName = "p")
                    AgwTypeNovedadReetiquetadoIn p);

    /**
     * sugerir Sifa
     *
     * @param p
     * @return returns https.sandbox_coordinadora_com.agw.ws.guias._1_6.server.AgwTypeSugerirSifaOut
     */
    @WebMethod(operationName = "Sifa_sugerirSifa", action = "https://sandbox.coordinadora.com/agw/ws/guias/1.6/server.php#Sifa_sugerirSifa")
    @WebResult(partName = "return")
    public AgwTypeSugerirSifaOut sifaSugerirSifa(
            @WebParam(name = "p", partName = "p")
                    AgwTypeSugerirSifaIn p);

    /**
     * liquidar Sifa
     *
     * @param p
     * @return returns https.sandbox_coordinadora_com.agw.ws.guias._1_6.server.AgwTypeLiquidarSifaOut
     */
    @WebMethod(operationName = "Sifa_liquidarSifa", action = "https://sandbox.coordinadora.com/agw/ws/guias/1.6/server.php#Sifa_liquidarSifa")
    @WebResult(partName = "return")
    public AgwTypeLiquidarSifaOut sifaLiquidarSifa(
            @WebParam(name = "p", partName = "p")
                    AgwTypeliquidarSifaIn p);

    /**
     * liquidar Full Tarifa Sifa
     *
     * @param p
     * @return returns https.sandbox_coordinadora_com.agw.ws.guias._1_6.server.AgwTypeLiquidarFullTarifaSifaOut
     */
    @WebMethod(operationName = "Sifa_liquidarFullTarifaSifa", action = "https://sandbox.coordinadora.com/agw/ws/guias/1.6/server.php#Sifa_liquidarFullTarifaSifa")
    @WebResult(partName = "return")
    public AgwTypeLiquidarFullTarifaSifaOut sifaLiquidarFullTarifaSifa(
            @WebParam(name = "p", partName = "p")
                    AgwTypeliquidarFullTarifaSifaIn p);

}
